AllCops:
  Exclude:
    - 'apps/web/application.rb'
    - 'db/**/*'
    - 'spec/**/*'
    - 'Rakefile'

ConditionalAssignment:
  Enabled: false
StringLiterals:
  Enabled: false
RedundantReturn:
  Enabled: false
Documentation:
  Enabled: false
WordArray:
  Enabled: false
AbcSize:
  Enabled: false
MutableConstant:
  Enabled: false
SignalException:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
MissingRespondToMissing:
  Enabled: false
MethodMissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Max: 120
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/ClassAndModuleChildren:
  Enabled: false
